Feat/responsive main
soolung/simblue-client pull request #41
Opened 2023-01-26 06:55 UTC by sookyoungwoo

## 📄 Summary
> 메인화면 반응형으로 수정

<br>

## 🔨 Tasks
- 배너 최소 길이 높임
- 신청 컴포넌트 반응형시 이보지 삭제
- 신청 컴포넌트 반응형시 폰트 체인지 
- 신청 컴포넌트 반응형시 2개씩 재배열

<br>

## 🙋🏻 More

2023-01-26 07:09 UTC, gimhanul requested changes
customAxios 있는 `server.js` 원래대로 돌려놔주새여

2023-01-26 08:21 UTC, gimhanul requested changes
https://github.com/soolung/simblue-client/blob/0eb332f7a87541840ec3485fdb2fc6cdd0ca319a/src/utils/axios/server.js#L9-L29

server.js 좀 바뀌어서 이케생김
들어가서 확인 ㄱㄱ

2023-01-30 05:46 UTC, SEOKKAMONI approved these changes

2023-01-30 16:16 UTC, gimhanul approved these changes

2023-01-30 16:17 UTC, gimhanul commented
기나긴 여정이었읍니다...
수고하셧읍니다...람쥐

2023-01-30 23:49 UTC, sookyoungwoo commented
드디어 나의 잔디가..

2023-01-30 23:49 UTC, merged